-- MySQL Script generated by MySQL Workbench
-- Mon Apr  2 09:27:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema football4th
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema football4th
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `football4th` DEFAULT CHARACTER SET utf8 ;
USE `football4th` ;

-- -----------------------------------------------------
-- Table `football4th`.`Organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`Organization` (
  `id_org` INT(11) NOT NULL AUTO_INCREMENT COMMENT '机构id',
  `school_code` INT(11) NULL DEFAULT NULL COMMENT '学校专属代码',
  `name` VARCHAR(255) NOT NULL COMMENT '机构名称',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  `province_code` INT(11) NOT NULL COMMENT '省编号',
  `province_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '省中文名称',
  `country_code` INT(11) NOT NULL COMMENT '县编号',
  `country_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '市中文名',
  `village_code` INT(11) NOT NULL COMMENT '乡编号',
  `village_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '乡镇中文名',
  `type` INT(11) NOT NULL COMMENT '类型0学校1机构',
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `salt` VARCHAR(255) NULL DEFAULT NULL COMMENT '加密',
  PRIMARY KEY (`id_org`),
  UNIQUE INDEX `id_org_UNIQUE` (`id_org` ASC),
  UNIQUE INDEX `school_code_UNIQUE` (`school_code` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10007
DEFAULT CHARACTER SET = utf8
COMMENT = '机构表';


-- -----------------------------------------------------
-- Table `football4th`.`Coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`Coach` (
  `id_coach` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_id` INT(11) NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `sex` INT(11) NOT NULL COMMENT '性别\n·1 男\n0 女',
  `idcard` VARCHAR(18) NOT NULL,
  `height` FLOAT NULL DEFAULT NULL,
  `weight` FLOAT NULL DEFAULT NULL,
  `status` INT(1) NOT NULL COMMENT '0 在职 1 离职',
  `phone` VARCHAR(20) NOT NULL,
  `photo` VARCHAR(50) NULL DEFAULT NULL,
  `score` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_coach`),
  UNIQUE INDEX `COACH_ID_UNIQUE` (`id_coach` ASC),
  UNIQUE INDEX `COACH_NAME_UNIQUE` (`name` ASC),
  UNIQUE INDEX `COACH_IDCARD_UNIQUE` (`idcard` ASC),
  UNIQUE INDEX `COACH_PHONG_UNIQUE` (`phone` ASC),
  INDEX `fk_Coach_Organization1_idx` (`org_id` ASC),
  CONSTRAINT `fk_Coach_Organization1`
    FOREIGN KEY (`org_id`)
    REFERENCES `football4th`.`Organization` (`id_org`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 50010
DEFAULT CHARACTER SET = utf8
COMMENT = '教练表';


-- -----------------------------------------------------
-- Table `football4th`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`Match` (
  `id_match` INT(11) NOT NULL AUTO_INCREMENT COMMENT '赛事ID',
  `org_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '赛事名称',
  `start_date` DATE NOT NULL COMMENT '开始时间',
  `end_date` DATE NULL DEFAULT NULL COMMENT '结束时间',
  `num_player` INT(11) NOT NULL COMMENT '赛制人数',
  `apply_deadline` DATETIME NOT NULL COMMENT '报名截止日期',
  `level` INT(11) NOT NULL COMMENT '赛事级别:\n0 校级\n1 县级\n2 市级\n3 省级',
  `status` INT(11) NOT NULL COMMENT '状态位: \n0 报名阶段\n1 赛事期间\n2 赛事结束\n3 删除',
  PRIMARY KEY (`id_match`),
  UNIQUE INDEX `id_match_UNIQUE` (`id_match` ASC),
  INDEX `fk_Match_Organization1_idx` (`org_id` ASC),
  CONSTRAINT `fk_Match_Organization1`
    FOREIGN KEY (`org_id`)
    REFERENCES `football4th`.`Organization` (`id_org`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `football4th`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`Team` (
  `id_team` INT(11) NOT NULL AUTO_INCREMENT COMMENT '球队编号默认从50000开始',
  `org_id` INT(11) NULL DEFAULT NULL COMMENT '机构编号',
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '球队名称',
  `type` INT(1) NOT NULL COMMENT '球队类型：小学1-6  .初中7-9. 混合(年级10、校级11）',
  `status` INT(1) NOT NULL COMMENT '0：在役 1：退役',
  `create_time` DATETIME NOT NULL COMMENT '球队创建时间',
  `team_sum` INT(11) NULL DEFAULT NULL COMMENT '球队人数',
  `team_score` INT(11) NULL DEFAULT NULL COMMENT '球队积分',
  `retire_time` DATETIME NULL DEFAULT NULL COMMENT '退役时间',
  PRIMARY KEY (`id_team`),
  UNIQUE INDEX `id_team_UNIQUE` (`id_team` ASC),
  INDEX `fk_Team_Organization1_idx` (`org_id` ASC),
  CONSTRAINT `fk_Team_Organization1`
    FOREIGN KEY (`org_id`)
    REFERENCES `football4th`.`Organization` (`id_org`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 100061
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `football4th`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`Schedule` (
  `id_schedule` INT(11) NOT NULL AUTO_INCREMENT COMMENT '赛程ID',
  `match_id` INT(11) NOT NULL COMMENT '赛事ID',
  `team_A` INT(11) NOT NULL COMMENT '主队ID',
  `team_B` INT(11) NOT NULL COMMENT '客队ID',
  `goal_A` INT(3) NOT NULL DEFAULT '0' COMMENT '主队进球数',
  `goal_B` INT(3) NOT NULL DEFAULT '0' COMMENT '客队进球数',
  `begin_time` DATETIME NOT NULL COMMENT '开赛时间',
  `place` VARCHAR(60) NOT NULL COMMENT '比赛场地',
  `status` INT(1) NOT NULL COMMENT '状态位: \n0 准备阶段\n1 正在比赛\n2 赛程结束\n3 删除',
  PRIMARY KEY (`id_schedule`),
  UNIQUE INDEX `id_schedule_UNIQUE` (`id_schedule` ASC),
  INDEX `fk_Schedule_Match_idx` (`match_id` ASC),
  INDEX `fk_Schedule_TeamA_idx` (`team_A` ASC),
  INDEX `fk_Schedule_TeamB_idx` (`team_B` ASC),
  CONSTRAINT `fk_Schedule_Match`
    FOREIGN KEY (`match_id`)
    REFERENCES `football4th`.`Match` (`id_match`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schedule_TeamA`
    FOREIGN KEY (`team_A`)
    REFERENCES `football4th`.`Team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schedule_TeamB`
    FOREIGN KEY (`team_B`)
    REFERENCES `football4th`.`Team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `football4th`.`Referee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`Referee` (
  `id_referee` INT(11) NOT NULL COMMENT '裁判ID',
  `id_sch` INT(11) NOT NULL COMMENT '赛程外键ID',
  `username` VARCHAR(45) NOT NULL COMMENT '用户名',
  `password` VARCHAR(45) NOT NULL COMMENT '密码',
  `status` INT(11) NOT NULL COMMENT '0 有效\n1 无效',
  `expire_time` DATETIME NULL DEFAULT NULL COMMENT '账号到期时间',
  `phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '电话',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '真实姓名',
  `idcard` VARCHAR(18) NULL DEFAULT NULL COMMENT '身份证号',
  `salt` VARCHAR(45) NULL DEFAULT NULL,
  `isCheck` INT(11) NULL DEFAULT '0' COMMENT '1已入场验证，0没有入场验证',
  PRIMARY KEY (`id_referee`),
  UNIQUE INDEX `id_referee_UNIQUE` (`id_referee` ASC),
  INDEX `fk_Referee_Schedule1_idx` (`id_sch` ASC),
  CONSTRAINT `fk_Referee_Schedule1`
    FOREIGN KEY (`id_sch`)
    REFERENCES `football4th`.`Schedule` (`id_schedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `football4th`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`Report` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_sch` INT(11) NOT NULL COMMENT '赛程外键',
  `id_ref` INT(11) NOT NULL COMMENT '裁判员外键',
  `result` INT(11) NULL DEFAULT NULL COMMENT '结局为空为平局，其余为获胜队伍id',
  `red_des` VARCHAR(200) NULL DEFAULT NULL COMMENT '红牌情况说明',
  `point_des` VARCHAR(100) NULL DEFAULT NULL COMMENT '点球罚球情况说明',
  `miss_des` VARCHAR(100) NULL DEFAULT NULL COMMENT '严重错漏判说明',
  `create_time` DATETIME NULL DEFAULT NULL,
  `status` INT(1) NULL DEFAULT NULL,
  `score_a` INT(3) NULL DEFAULT NULL COMMENT '主队得分',
  `score_b` INT(3) NULL DEFAULT NULL COMMENT '客队得分',
  PRIMARY KEY (`id`),
  INDEX `Report_Schedule_FK` (`id_sch` ASC),
  INDEX `Report_Team_FK` (`result` ASC),
  INDEX `Report_Referee_FK` (`id_ref` ASC),
  CONSTRAINT `Report_Referee_FK`
    FOREIGN KEY (`id_ref`)
    REFERENCES `football4th`.`Referee` (`id_referee`),
  CONSTRAINT `Report_Schedule_FK`
    FOREIGN KEY (`id_sch`)
    REFERENCES `football4th`.`Schedule` (`id_schedule`),
  CONSTRAINT `Report_Team_FK`
    FOREIGN KEY (`result`)
    REFERENCES `football4th`.`Team` (`id_team`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8
COMMENT = '裁判报告书表';


-- -----------------------------------------------------
-- Table `football4th`.`Judgement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`Judgement` (
  `id_report` INT(11) NOT NULL COMMENT '报告书编号',
  `id_team` INT(11) NULL DEFAULT NULL,
  `player_name` VARCHAR(16) NULL DEFAULT NULL COMMENT '球员名字',
  `player_positon` VARCHAR(10) NULL DEFAULT NULL COMMENT '球员位置',
  `player_number` INT(11) NULL DEFAULT NULL COMMENT '球员号码',
  `type` INT(1) NULL DEFAULT NULL COMMENT '状态类型1首发，2替补，3进球，4警告，5判罚',
  `other` VARCHAR(50) NULL DEFAULT NULL COMMENT '其他，如警告原因',
  `create_time` DATETIME NULL DEFAULT NULL COMMENT '各种时间，如首发时间，进场时间',
  INDEX `Judgement_Report_FK` (`id_report` ASC),
  CONSTRAINT `Judgement_Report_FK`
    FOREIGN KEY (`id_report`)
    REFERENCES `football4th`.`Report` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '裁判报告书球员信息';


-- -----------------------------------------------------
-- Table `football4th`.`Live`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`Live` (
  `id_live` INT(11) NOT NULL AUTO_INCREMENT COMMENT '图文直播ID',
  `id_sch` INT(11) NOT NULL COMMENT '赛程外键ID',
  `phone` VARCHAR(20) NOT NULL COMMENT '发送人电话',
  `content` VARCHAR(255) NOT NULL COMMENT '内容',
  `send_time` DATETIME NOT NULL COMMENT '发送时间',
  `status` INT(11) NOT NULL COMMENT '0 无效\n1 有效',
  `img` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_live`),
  INDEX `fk_Live_Schedule1_idx` (`id_sch` ASC),
  CONSTRAINT `fk_Live_Schedule1`
    FOREIGN KEY (`id_sch`)
    REFERENCES `football4th`.`Schedule` (`id_schedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 182
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `football4th`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`Player` (
  `id_player` INT(11) NOT NULL AUTO_INCREMENT COMMENT '球员id',
  `username` VARCHAR(12) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `org_id` INT(11) NOT NULL,
  `grade` INT(11) NOT NULL COMMENT '年级',
  `classes` VARCHAR(255) NOT NULL COMMENT '班级',
  `headpic` VARCHAR(255) NULL DEFAULT NULL COMMENT '球员头像',
  `salt` VARCHAR(255) NULL DEFAULT NULL COMMENT '加密',
  `status` INT(1) NULL DEFAULT NULL COMMENT '0正常 1离校 2删除',
  `score` INT(11) NULL DEFAULT NULL COMMENT '球员积分',
  `sex` VARCHAR(2) NULL DEFAULT NULL,
  `idcard` VARCHAR(18) NULL DEFAULT NULL,
  PRIMARY KEY (`id_player`, `username`),
  INDEX `fk_Player_Organization1_idx` (`org_id` ASC),
  CONSTRAINT `fk_Player_Organization1`
    FOREIGN KEY (`org_id`)
    REFERENCES `football4th`.`Organization` (`id_org`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1000010
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `football4th`.`M_Match_Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`M_Match_Staff` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `match_id` INT(11) NOT NULL,
  `org_id` INT(11) NOT NULL,
  `team_id` INT(11) NOT NULL,
  `player_id` INT(11) NOT NULL,
  `status` INT(11) NOT NULL COMMENT '0 未审核\n1 正常参赛',
  PRIMARY KEY (`id`),
  INDEX `fk_MatchStaff_Match1_idx` (`match_id` ASC),
  INDEX `fk_MatchStaff_Org1_idx` (`org_id` ASC),
  INDEX `fk_MatchStaff_Team1_idx` (`team_id` ASC),
  INDEX `fk_MatchStaff_Player1_idx` (`player_id` ASC),
  CONSTRAINT `fk_MatchStaff_Match1`
    FOREIGN KEY (`match_id`)
    REFERENCES `football4th`.`Match` (`id_match`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MatchStaff_Org1`
    FOREIGN KEY (`org_id`)
    REFERENCES `football4th`.`Organization` (`id_org`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MatchStaff_Player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `football4th`.`Player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MatchStaff_Team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `football4th`.`Team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `football4th`.`M_Sch_Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`M_Sch_Staff` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `player_id` INT(11) NOT NULL,
  `sch_id` INT(11) NOT NULL,
  `team_id` INT(11) NOT NULL,
  `time` DATETIME NOT NULL COMMENT '出场时间',
  PRIMARY KEY (`id`),
  INDEX `fk_M_Sch_Staff_Schedule1_idx` (`sch_id` ASC),
  INDEX `fk_M_Sch_Staff_Player1_idx` (`player_id` ASC),
  INDEX `fk_M_Sch_Staff_Team1_idx` (`team_id` ASC),
  CONSTRAINT `fk_M_Sch_Staff_Player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `football4th`.`Player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_M_Sch_Staff_Schedule1`
    FOREIGN KEY (`sch_id`)
    REFERENCES `football4th`.`Schedule` (`id_schedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_M_Sch_Staff_Team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `football4th`.`Team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 138
DEFAULT CHARACTER SET = utf8
COMMENT = '赛程出场人员';


-- -----------------------------------------------------
-- Table `football4th`.`M_Team_Coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`M_Team_Coach` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `team_id` INT(11) NOT NULL,
  `coach_id` INT(11) NOT NULL,
  `out_time` DATETIME NULL DEFAULT NULL COMMENT '教练离开球队时间',
  `join_time` DATETIME NOT NULL COMMENT '教练加入球队时间',
  `status` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 108
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `football4th`.`M_Team_Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `football4th`.`M_Team_Player` (
  `player_id` INT(11) NOT NULL,
  `team_id` INT(11) NOT NULL,
  `join_time` DATETIME NOT NULL COMMENT '加入时间',
  `status` INT(11) NOT NULL COMMENT '0 正常\n1 离队\n',
  `out_time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`player_id`, `team_id`),
  INDEX `fk_M_Team_Player_player1_idx` (`player_id` ASC),
  INDEX `fk_M_Team_Player_Team1_idx` (`team_id` ASC),
  CONSTRAINT `fk_M_Team_Player_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `football4th`.`Player` (`id_player`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_M_Team_Player_Team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `football4th`.`Team` (`id_team`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '球队和球员映射表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
